import os

os.getcwd()

os.chdir("Livro-Python-Introducao")
print(os.getcwd())
os.chdir("a")
print(os.getcwd())
os.chdir("..")
print(os.getcwd())
os.chdir("b")
print(os.getcwd())
os.chdir("../c")
print(os.getcwd())
os.chdir("..")

os.mkdir("d")
os.mkdir("e")
os.mkdir("f")

print(os.getcwd())
os.chdir("d")
print(os.getcwd())
os.chdir("../e")
print(os.getcwd())
os.chdir("..")
print(os.getcwd())
os.chdir("f")
print(os.getcwd())
os.chdir("..")